#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="dbnsFoam"

paraFoam -touch
runApplication blockMesh
runApplication $application # | sudo perf record
