#!/bin/bash

# Resource GMSH, just in case
GMSH="/home/thomas/gmsh-3.0.6-Linux64/bin/gmsh"

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean everything in here
cleanCase
rm -rf perf*
rm -rf log*

# Generate the mesh, copy it and get the polyMesh with gmshtofoam
#rm -rf constant/polyMesh
#$GMSH -3 ./constant/gmshmesh/shocktube.geo -o ./constant/gmshmesh/shocktube.msh
#cp constant/gmshmesh/shocktube.msh .
#gmshToFoam shocktube.msh
#rm -rf shocktube.msh

#blockMesh
