#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh

# Create sets for later creating the cyclics
runApplication topoSet

# Create cyclics from the sets
runApplication createPatch -overwrite

runApplication boxTurb
runApplication $application
runApplication enstrophy

# ----------------------------------------------------------------- end-of-file
