#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="incredibleSolver"


cp -rf 0/p.orig 0/p
cp -rf 0/T.orig 0/T
cp -rf 0/U.orig 0/U
rm -rf 0/*TALE
rm -rf 0/rho

# runApplication blockMesh
runApplication paraFoam -touch
runApplication $application # | sudo perf record
