#!/bin/sh

GMSH="/home/thomas/gmsh-3.0.6-Linux64/bin/gmsh"

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf perf*

rm -rf constant/polyMesh
$GMSH -3 ./constant/gmshmesh/shocktube.geo -o ./constant/gmshmesh/shocktube.msh
echo yes
cp constant/gmshmesh/shocktube.msh .
gmshToFoam shocktube.msh
rm -rf shocktube.msh

python3 0/init/set_init_fields.py 12288
paraFoam -touch
