#!/bin/bash

# Resource GMSH, just in case
GMSH="/home/thomas/gmsh-3.0.6-Linux64/bin/gmsh"

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean everything in here
cleanCase
rm -rf perf*

# Generate the mesh, copy it and get the polyMesh with gmshtofoam
rm -rf constant/polyMesh
$GMSH -3 ./constant/gmshmesh/shocktube.geo -o ./constant/gmshmesh/shocktube.msh
cp constant/gmshmesh/shocktube.msh .
gmshToFoam shocktube.msh
rm -rf shocktube.msh

# Get index of faces
# it corresponds to index where bounds start
gerard=($(cat constant/polyMesh/boundary | awk -F 'startFace' '{print $2}' |  grep . | tr ';' ' ' | tr '\n' ' '))
echo "${gerard[0]}" "${gerard[1]}" "${gerard[2]}" "${gerard[3]}" "${gerard[4]}" "${gerard[5]}"

# Generate modified initial conditions
python3 0/init/set_init_fields.py 934

# Generate the paraview guide file
paraFoam -touch
