#!/bin/bash

# Resource GMSH, just in case
GMSH="/home/thomas/gmsh-3.0.6-Linux64/bin/gmsh"

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean everything in here
cleanCase
rm -rf perf*

# Get mesh
cp constant/gmshmesh/squarepipe.msh .
gmshToFoam squarepipe.msh
rm squarepipe.msh

# Gget conditions
rm 0/init/internalp
python3 0/init/generate_pressure.py
mv internalp 0/init/

# Generate the paraview guide file
paraFoam -touch
