#!/bin/bash                                                                                                                                                                                                                                   

# Resource GMSH, just in case                                                                                                                                                                                                                 
GMSH="/home/thomas/gmsh-3.0.6-Linux64/bin/gmsh"

# Source tutorial clean functions                                                                                                                                                                                                             
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean everything in here                                                                                                                                                                                                                    
cleanCase
rm -rf perf*
rm -rf log*
