#!/bin/bash                                                                                                                                                                               # Source tutorial clean functions                                                                                                                                                                                                             
#. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean everything in here                                                                                                                                                                                                                    
#cleanCase
rm -rf perf*
rm -rf log*
rm *.* 1 2 -rf
